#!/usr/bin/awk -f

# This source file is part of the Swift.org open source project
#
# Copyright (c) 2014 - 2020 Apple Inc. and the Swift project authors
# Licensed under Apache License v2.0 with Runtime Library Exception
#
# See https://swift.org/LICENSE.txt for license information
# See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors

BEGIN {
  FS = ", "
  OFS = ", "
  print "Pass Name", "Lost Variables", "Killed Variables"
}

$1 == "function" && $2 == "lostvars" {
  lost[$4] += $6
  passes[$4] = 1
}

$1 == "function" && $2 == "killedvars" {
  killed[$4] += $6
  passes[$4] = 1
}

END {
  for (i in passes)
    print i, lost[i] + 0, killed[i] + 0
}
